os: osx
language: node_js
node_js: stable
cache:
  directories:
    - node_modules
before_install:
- brew update && brew install git-lfs
- git lfs install
install:
- npm install
before_script:
- git lfs pull
script:
- npm run build
deploy:
  provider: releases
  api_key:
    secure: ZlyvUoj/FR5MNpsllTPurX/PAGwJhaUxbo4Rrdgbl+md9hPaj2DPQy4Xjzf6uxaZaXp+ZDNKQDxXV4FX3URjhyB4lg6rXzRi4Ggl/AgSl4rhxRWUZnC+S0uOoSe2llDrarOm26xjk04dsvFmGJCOBhRrfVKgBH7Seka3x2Qgm9xWXWxA4RdhMk9FWM2HMjDSHjC24hgl6Pu5MQe6DQCF6dcdazV+3ofp80qk7Jj6fafltP2XhHdsBbxWtd56eTPCmUdzuAUKFjxejS4QSQwtls8xGIPT/SyxnBBG7Hr3hdIbdEjoLaU87Vu4j3gApaovHaapnCMB9zywco9Tc3e6MqIGPe0I2sWs4auO/MiRTMIOAqZH5cGvHr/mB6HAZniqnqUgwcaMAwSTIRukTKENmw8BmN4v3qCJaLolyyzp3ufYuwsL7mXrW4GI63HN6q4SDgFg9v8A0bLnp7LIy5ocxnYnjXMd+tUYW3xJRAoeQa+F1s/QlvIyG+kq/2SnBC7t/kdA5ZMMfxNAshewx7kDSYNqj+X6tlwsAr/Khg9zCa6oyUb2g7sNwIHL0CZx0MkG3a5Iu9UycFEZJJZE/O5lQxuiBTLx1/c/+qis/DAxYOGzpOwx1Bwrjj5puWshEdRym9wfHTh6kwhaej9HvvzxqP0R/p9h1bs8Ogaaq637jrI=
  file: people-box.zip
  skip_cleanup: true
  on:
    repo: delucis/people-box
    tags: true
